#!/bin/bash
set -e

mkdir -p docs
rm -rf docs/*

node_modules/.bin/docco -t resources/docco.jst source/*
node_modules/.bin/coffee -co docs/javascripts resources/interactive.litcoffee

cp -r resources/docco.css resources/public docs
cp resources/*.js docs/javascripts
cp dist/pixie_canvas.js docs/javascripts
